# Based on https://github.com/hedgedoc/hedgedoc/blob/c2854957a2b4c74dacc664cb0f497b6f50b55d1e/docs/content/setup/docker.md

services:
  hedgedoc:
    image: quay.io/hedgedoc/hedgedoc:1.9.8
    restart: always
    depends_on:
      - database
    volumes:
      - ./volumes/hedgedoc_uploads:/hedgedoc/public/uploads
    environment:
      - CMD_DB_URL=postgres://hedgedoc:password@database:5432/hedgedoc
      - CMD_DOMAIN=${HEDGEDOC_CMD_DOMAIN:?}
      - CMD_PROTOCOL_USESSL=${HEDGEDOC_CMD_PROTOCOL_USESSL:?}
      - CMD_URL_ADDPORT=${HEDGEDOC_CMD_URL_ADDPORT:?}
      - CMD_SESSION_SECRET=${HEDGEDOC_CMD_SESSION_SECRET:?}
      - CMD_ALLOW_EMAIL_REGISTER=${HEDGEDOC_CMD_ALLOW_EMAIL_REGISTER:?}

  database:
    image: postgres:15
    restart: always
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hedgedoc
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hedgedoc

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - hedgedoc
    volumes:
      - ./nginx_templates:/etc/nginx/templates
      - ${NGINX_LOG_DIR:?}:/logs
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.nginx

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    restart: always
    depends_on:
      - nginx
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TUNNEL_TOKEN:?}
